#!/bin/zsh

PREZTO_REPO_URL="https://github.com/sorin-ionescu/prezto.git"
if git ls-remote "$PREZTO_REPO_URL" &>/dev/null; then
  echo "Fetching Prezto:"
  if [ ! -d "$HOME/.zprezto" ]; then
    echo "Cloning to ~/.zprezto:"
    git clone --recursive "$PREZTO_REPO_URL" ~/.zprezto

    setopt EXTENDED_GLOB
    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    done
  else
    (
      cd ~/.zprezto
      git pull
    )
  fi
fi
